export * from './delegua-provedor-completude';
export * from './delegua-testes-provedor-completude';
export * from './delprops-provedor-completude';
export * from './foles-provedor-completude';
export * from './liquido-provedor-completude';
export * from './lmht-provedor-completude';
export * from './pitugues-provedor-completude';
export * from './visualg-provedor-completude';
export * from './portugol-studio-provedor-completude';