algoritmo "teste5"

var

    num1, num2: inteiro
    texto1, texto2: caractere

    teste: logico

inicio
    teste <- verdadeiro
    leia (num1)

    escreval(teste)

    // teste 1 enquanto, faça, fimenquanto, sem (), sem {}
    enquanto teste = verdadeiro faca

        escreval("num1 não é maior que 0")
        leia (num1)

        se num1 > 0 entao
            teste <- falso
        fimse
    fimenquanto

    escreval("num1 é maior que 0")

fimalgoritmo