algoritmo "Comandos de Decisão"
// Declaração de variáveis
var
    num1, num2: real
inicio
    // Seção de Comandos, procedimento, funções, etc
    escreval("Digite o primeiro número: ")
    leia(num1)
    escreval("Digite o segundo número: ")
    leia(num2)

    se (num1 > num2) então 
        escreva ("O primeiro número é maior!")
    fimse
    
    se (num1 < num2) então 
        escreva ("O segundo número é maior!")
    fimse

fimalgoritmo