algoritmo "Realiza Cálculos"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
procedimento realizaCalculos(x, y: inteiro)
var
inicio
fimprocedimento

var
    num1, num2: inteiro

inicio

    leia(num1)
    leia(num2)
    realizaCalculos(num1, num2)

fimalgoritmo